name: Build and Deploy Pipeline
#Trigger will work only when the code is pushed to the branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repo
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installing pnpm package
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm run build

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deployment part
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          cd /home/deployerdev/coding/projects/primelogic-solutions/

          # Pull latest changes
          git pull origin main

          # Install dependencies
          pnpm install --frozen-lockfile

          # Build the project
          pnpm build

          # Restart the service using PM2 or systemd
          pm2 restart my-backend || pm2 start dist/src/server.js --name "my-backend"
          pm2 save 
          EOF 
          # hello
